### PR TITLE
Added my intro

### PR DESCRIPTION
**Pull request by Shubham-Kukreti**

### CODE REVIEW

**Comment by NishkarshRaj** [comment]
@Shubham-Kukreti why have you closed this PR?

**Comment by Shubham-Kukreti** [comment]
> @Shubham-Kukreti why have you closed this PR?

One of the checks keeps failing again and again that's why I closed the PR.

**Comment by NishkarshRaj** [comment]
> > @Shubham-Kukreti why have you closed this PR?
> 
> One of the checks keeps failing again and again that's why I closed the PR.

That is because the GitHub Actions bot is failing it. Not your fault.

**Comment by Shubham-Kukreti** [comment]
> > > @Shubham-Kukreti why have you closed this PR?
> > 
> > One of the checks keeps failing again and again that's why I closed the PR.
> 
> That is because the GitHub Actions bot is failing it. Not your fault.

Okay I'll just make the PR again. Thanks.

**Comment by NishkarshRaj** [comment]
> > > > @Shubham-Kukreti why have you closed this PR?
> > > 
> > > 
> > > One of the checks keeps failing again and again that's why I closed the PR.
> > 
> > 
> > That is because the GitHub Actions bot is failing it. Not your fault.
> 
> Okay I'll just make the PR again. Thanks.

No need. Just reopen this one.

**Pull request closed without merging**
