### PR TITLE
Introduction | Mayankjha997

### PR DESCRIPTION
**Pull request by Mayankjha997**
This is my first contribution.

### CODE REVIEW

**Review by NishkarshRaj — CHANGES_REQUESTED** [review]
@Mayankjha997 

* The image you have attached is not in repository - push that as well.
* This introduction must be kept in `intro/mayank-jha.md`
* Your headings must not have values within []

Make these changes!

**Review by NishkarshRaj — CHANGES_REQUESTED** [review]
@Mayankjha997 don't add images as drive links!
Please post images in png/jpg format only

**Review by Mayankjha997 — COMMENTED** [review]
please check

**Comment by Mayankjha997** [comment]
@NishkarshRaj  please check

**Comment by NishkarshRaj** [comment]
> 
> 
> please check

On it @Mayankjha997

**Comment by NishkarshRaj** [comment]
@Mayankjha997 I have made some changes - Image cannot be added as a text file as it increases build time.

If you want to add image in img/ - upload files in png or jpeg format only.

If you are fine with the changes I have made, I would merge the PR after another review.

**Comment by Mayankjha997** [comment]
yes please merge

**Comment by Mayankjha997** [comment]
@NishkarshRaj  is it done?

**Comment by NishkarshRaj** [comment]
> 
> 
> yes please merge

Congrats on your PR :) It will be merged!

Advice: Please follow the guidelines carefully going forward and be more formal. Hopeful you have a great journey ahead in Open Source community.

**Pull request merged**
